import React from 'react';
import { Page } from '../types';
import { PublicHeader } from './PublicHeader';
import { DISCLAIMER } from '../constants';

const DisclaimerPage: React.FC<{ onNavigate: (page: Page) => void }> = ({ onNavigate }) => {
    return (
        <div className="bg-white dark:bg-slate-900">
            <PublicHeader onNavigate={onNavigate} />
            <main className="container mx-auto px-4 py-20 md:py-28">
                <div className="max-w-4xl mx-auto text-center">
                    <h1 className="text-4xl md:text-5xl font-extrabold text-slate-800 dark:text-slate-100 tracking-tighter">Legal Disclaimer</h1>
                     <p className="mt-4 text-lg text-slate-600 dark:text-slate-400">Important Information Regarding Your Use of Our Platform</p>

                    <div className="mt-12 text-left bg-yellow-50 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-700/50 rounded-lg p-8 space-y-6 text-yellow-800 dark:text-yellow-200">
                        <h2 className="text-2xl font-bold">Not Legal Advice</h2>
                        <p>
                            Our platform is a software tool that provides AI-powered assistance for drafting and reviewing legal documents. The information, content, and documents generated by our Service are for informational purposes only and do not constitute legal advice.
                        </p>
                        
                        <h2 className="text-2xl font-bold">No Attorney-Client Relationship</h2>
                        <p>
                            Your use of the Service, including any communication with us, does not create an attorney-client relationship. We are a technology company, not a law firm. Information you provide to us is not protected by attorney-client privilege.
                        </p>

                        <h2 className="text-2xl font-bold">Requirement for Professional Review</h2>
                        <p>
                           <strong>{DISCLAIMER}</strong> The law is complex and varies significantly by jurisdiction. The AI-generated content may not be accurate, complete, or suitable for your specific circumstances. You are solely responsible for reviewing and validating any output from the Service with a qualified attorney licensed to practice in the relevant jurisdiction before relying on or using it.
                        </p>
                        
                        <h2 className="text-2xl font-bold">No Warranties</h2>
                        <p>
                            The Service is provided "AS IS" without any warranties of any kind, express or implied. We do not warrant the accuracy, reliability, or completeness of any information or documents generated by the Service. Your use of the Service is at your own risk.
                        </p>

                        <div className="text-center pt-6 border-t border-yellow-300 dark:border-yellow-700/50">
                            <button onClick={() => onNavigate('signup')} className="px-6 py-3 font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700">
                                I Understand, Start Free Trial
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};

export default DisclaimerPage;